# Generated by Django 3.2 on 2022-12-07 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='artikel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=250)),
                ('isi', models.TextField()),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('sumber', models.CharField(max_length=100)),
                ('gambar', models.ImageField(upload_to='')),
                ('slug', models.SlugField(editable=False)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('sifat', models.CharField(max_length=100)),
                ('jenis', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
