# Generated by Django 3.2 on 2022-12-07 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petugas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='gambar',
            field=models.ImageField(upload_to='berita/'),
        ),
    ]
