# Generated by Django 3.2 on 2022-12-09 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auntentifikasi', '0001_initial'),
        ('petugas', '0002_alter_artikel_gambar'),
    ]

    operations = [
        migrations.CreateModel(
            name='pengaduan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('jalan', models.CharField(max_length=200)),
                ('kecamatan', models.CharField(max_length=100)),
                ('keterangan', models.CharField(max_length=300)),
                ('foto', models.ImageField(upload_to='pengaduan/')),
                ('kategori_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petugas.kategori')),
                ('pengadu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auntentifikasi.userprofileinfo')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
