# Generated by Django 3.2 on 2022-12-09 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petugas', '0004_pengaduan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengaduan',
            name='tanggal',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
