# Generated by Django 3.2 on 2022-12-09 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auntentifikasi', '0001_initial'),
        ('petugas', '0005_pengaduan_tanggal'),
    ]

    operations = [
        migrations.CreateModel(
            name='aduan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('jalan', models.CharField(max_length=200)),
                ('kecamatan', models.CharField(max_length=100)),
                ('keterangan', models.CharField(max_length=300)),
                ('foto', models.ImageField(upload_to='pengaduan/')),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('proses', 'Proses'), ('konfirmasi', 'Konfirmasi'), ('tolak', 'Tolak')], default='proses', max_length=50)),
                ('slug', models.SlugField(editable=False)),
                ('kategori_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petugas.kategori')),
                ('pengadu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auntentifikasi.userprofileinfo')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.DeleteModel(
            name='pengaduan',
        ),
    ]
