# Generated by Django 3.2 on 2022-12-09 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petugas', '0006_auto_20221209_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aduan',
            name='status',
            field=models.CharField(default='proses', max_length=50),
        ),
    ]
